# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'fire.ui'
##
## Created by: Qt User Interface Compiler version 6.5.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDoubleSpinBox, QFormLayout,
    QGridLayout, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QTextBrowser,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1265, 710)
        MainWindow.setMinimumSize(QSize(1265, 710))
        MainWindow.setMaximumSize(QSize(1265, 710))
        icon = QIcon()
        icon.addFile(u"icon/1000LOGO.jpg", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"#centralwidget{\n"
"background-color: rgb(240, 160, 100);\n"
"color: #FFFFFF; \n"
"}")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_weights = QLabel(self.centralwidget)
        self.label_weights.setObjectName(u"label_weights")
        self.label_weights.setGeometry(QRect(20, 50, 54, 16))
        font = QFont()
        font.setFamilies([u"\u963f\u91cc\u5df4\u5df4\u666e\u60e0\u4f53 Medium"])
        font.setPointSize(12)
        self.label_weights.setFont(font)
        self.label_source = QLabel(self.centralwidget)
        self.label_source.setObjectName(u"label_source")
        self.label_source.setGeometry(QRect(20, 100, 81, 16))
        self.label_source.setFont(font)
        self.label_conf = QLabel(self.centralwidget)
        self.label_conf.setObjectName(u"label_conf")
        self.label_conf.setGeometry(QRect(20, 150, 51, 16))
        self.label_conf.setFont(font)
        self.label_iou = QLabel(self.centralwidget)
        self.label_iou.setObjectName(u"label_iou")
        self.label_iou.setGeometry(QRect(160, 150, 31, 16))
        self.label_iou.setFont(font)
        self.doubleSpinBox_conf = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_conf.setObjectName(u"doubleSpinBox_conf")
        self.doubleSpinBox_conf.setGeometry(QRect(70, 150, 71, 22))
        self.doubleSpinBox_conf.setMaximum(1.000000000000000)
        self.doubleSpinBox_conf.setSingleStep(0.010000000000000)
        self.doubleSpinBox_conf.setValue(0.250000000000000)
        self.doubleSpinBox_iou = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_iou.setObjectName(u"doubleSpinBox_iou")
        self.doubleSpinBox_iou.setGeometry(QRect(200, 150, 71, 22))
        self.doubleSpinBox_iou.setMaximum(1.000000000000000)
        self.doubleSpinBox_iou.setSingleStep(0.010000000000000)
        self.doubleSpinBox_iou.setValue(0.450000000000000)
        self.gridLayoutWidget = QWidget(self.centralwidget)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(100, 90, 181, 42))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.pushButton_video = QPushButton(self.gridLayoutWidget)
        self.pushButton_video.setObjectName(u"pushButton_video")
        self.pushButton_video.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_video.setStyleSheet(u"border: none;")
        icon1 = QIcon()
        icon1.addFile(u"icon/\u89c6\u9891_video.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_video.setIcon(icon1)
        self.pushButton_video.setIconSize(QSize(32, 32))

        self.gridLayout.addWidget(self.pushButton_video, 0, 1, 1, 1)

        self.pushButton_img = QPushButton(self.gridLayoutWidget)
        self.pushButton_img.setObjectName(u"pushButton_img")
        self.pushButton_img.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_img.setStyleSheet(u"border: none;")
        icon2 = QIcon()
        icon2.addFile(u"icon/\u7167\u7247_pic.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_img.setIcon(icon2)
        self.pushButton_img.setIconSize(QSize(32, 32))

        self.gridLayout.addWidget(self.pushButton_img, 0, 0, 1, 1)

        self.pushButton_camera = QPushButton(self.gridLayoutWidget)
        self.pushButton_camera.setObjectName(u"pushButton_camera")
        self.pushButton_camera.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_camera.setStyleSheet(u"border: none;")
        icon3 = QIcon()
        icon3.addFile(u"icon/\u6444\u50cf\u5934_camera-one.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_camera.setIcon(icon3)
        self.pushButton_camera.setIconSize(QSize(32, 32))

        self.gridLayout.addWidget(self.pushButton_camera, 0, 2, 1, 1)

        self.lineEdit_weights = QLineEdit(self.centralwidget)
        self.lineEdit_weights.setObjectName(u"lineEdit_weights")
        self.lineEdit_weights.setGeometry(QRect(60, 40, 171, 31))
        self.lineEdit_weights.setStyleSheet(u"background-color: rgb(240, 160, 100);")
        self.pushButton_weights = QPushButton(self.centralwidget)
        self.pushButton_weights.setObjectName(u"pushButton_weights")
        self.pushButton_weights.setGeometry(QRect(230, 40, 56, 32))
        self.pushButton_weights.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_weights.setStyleSheet(u"border: none;")
        icon4 = QIcon()
        icon4.addFile(u"icon/\u6587\u4ef6\u5939-\u5f00_folder-open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_weights.setIcon(icon4)
        self.pushButton_weights.setIconSize(QSize(32, 32))
        self.formLayoutWidget = QWidget(self.centralwidget)
        self.formLayoutWidget.setObjectName(u"formLayoutWidget")
        self.formLayoutWidget.setGeometry(QRect(300, 90, 951, 531))
        self.formLayout = QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.label_result = QLabel(self.centralwidget)
        self.label_result.setObjectName(u"label_result")
        self.label_result.setGeometry(QRect(300, 82, 949, 581))
        self.label_result.setStyleSheet(u"border: 1px solid white;\n"
"background-color:white")
        self.label_result.setPixmap(QPixmap(u"icon/test.png"))
        self.pushButton_zz = QPushButton(self.centralwidget)
        self.pushButton_zz.setObjectName(u"pushButton_zz")
        self.pushButton_zz.setGeometry(QRect(310, 620, 56, 32))
        self.pushButton_zz.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_zz.setStyleSheet(u"border: none;")
        icon5 = QIcon()
        icon5.addFile(u"icon/zz.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_zz.setIcon(icon5)
        self.pushButton_zz.setIconSize(QSize(32, 32))
        self.pushButton_speed = QPushButton(self.centralwidget)
        self.pushButton_speed.setObjectName(u"pushButton_speed")
        self.pushButton_speed.setGeometry(QRect(20, 280, 41, 32))
        self.pushButton_speed.setStyleSheet(u"border: none;")
        icon6 = QIcon()
        icon6.addFile(u"icon/\u901f\u5ea6_speed-one.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_speed.setIcon(icon6)
        self.pushButton_speed.setIconSize(QSize(32, 32))
        self.label_speed = QLabel(self.centralwidget)
        self.label_speed.setObjectName(u"label_speed")
        self.label_speed.setGeometry(QRect(70, 280, 91, 31))
        font1 = QFont()
        font1.setFamilies([u"\u963f\u91cc\u5df4\u5df4\u666e\u60e0\u4f53"])
        font1.setPointSize(14)
        font1.setBold(True)
        self.label_speed.setFont(font1)
        self.label_alarm_level = QLabel(self.centralwidget)
        self.label_alarm_level.setObjectName(u"label_alarm_level")
        self.label_alarm_level.setGeometry(QRect(20, 200, 101, 16))
        self.label_alarm_level.setFont(font)
        self.textBrowser_result = QTextBrowser(self.centralwidget)
        self.textBrowser_result.setObjectName(u"textBrowser_result")
        self.textBrowser_result.setGeometry(QRect(10, 320, 281, 341))
        self.label_title = QLabel(self.centralwidget)
        self.label_title.setObjectName(u"label_title")
        self.label_title.setGeometry(QRect(580, 30, 351, 31))
        font2 = QFont()
        font2.setFamilies([u"\u963f\u91cc\u5df4\u5df4\u666e\u60e0\u4f53 Heavy"])
        font2.setPointSize(18)
        font2.setBold(True)
        self.label_title.setFont(font2)
        self.pushButton_logo = QPushButton(self.centralwidget)
        self.pushButton_logo.setObjectName(u"pushButton_logo")
        self.pushButton_logo.setGeometry(QRect(1180, 20, 56, 32))
        self.pushButton_logo.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_logo.setStyleSheet(u"border: none;")
        self.pushButton_logo.setIcon(icon)
        self.pushButton_logo.setIconSize(QSize(32, 32))
        self.label_is_save = QLabel(self.centralwidget)
        self.label_is_save.setObjectName(u"label_is_save")
        self.label_is_save.setGeometry(QRect(20, 240, 111, 16))
        self.label_is_save.setFont(font)
        self.checkBox_is_save = QCheckBox(self.centralwidget)
        self.checkBox_is_save.setObjectName(u"checkBox_is_save")
        self.checkBox_is_save.setGeometry(QRect(130, 240, 21, 21))
        self.checkBox_is_save.setIconSize(QSize(32, 32))
        self.checkBox_is_alarm = QCheckBox(self.centralwidget)
        self.checkBox_is_alarm.setObjectName(u"checkBox_is_alarm")
        self.checkBox_is_alarm.setGeometry(QRect(130, 200, 21, 21))
        self.checkBox_is_alarm.setIconSize(QSize(32, 32))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u706b\u707e\u70df\u96fe\u68c0\u6d4b\u8b66\u62a5\u7cfb\u7edfyolov5", None))
        self.label_weights.setText(QCoreApplication.translate("MainWindow", u"\u6743\u91cd\uff1a", None))
        self.label_source.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u8d44\u6e90\uff1a", None))
        self.label_conf.setText(QCoreApplication.translate("MainWindow", u"conf\uff1a", None))
        self.label_iou.setText(QCoreApplication.translate("MainWindow", u"iou:", None))
#if QT_CONFIG(tooltip)
        self.pushButton_video.setToolTip(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u89c6\u9891", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_video.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton_img.setToolTip(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u56fe\u7247", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_img.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton_camera.setToolTip(QCoreApplication.translate("MainWindow", u"\u5f00\u542f/\u5173\u95ed\u6444\u50cf\u5934", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_camera.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton_weights.setToolTip(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u6743\u91cd", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_weights.setText("")
        self.label_result.setText("")
#if QT_CONFIG(tooltip)
        self.pushButton_zz.setToolTip(QCoreApplication.translate("MainWindow", u"\u7ec8\u6b62\u68c0\u6d4b", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_zz.setText("")
        self.pushButton_speed.setText("")
        self.label_speed.setText(QCoreApplication.translate("MainWindow", u"00.00ms", None))
        self.label_alarm_level.setText(QCoreApplication.translate("MainWindow", u"\u662f\u5426\u53d1\u8b66\u62a5\u58f0\uff1a", None))
#if QT_CONFIG(tooltip)
        self.textBrowser_result.setToolTip(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u68c0\u6d4b\u7ed3\u679c", None))
#endif // QT_CONFIG(tooltip)
        self.textBrowser_result.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u7ed3\u679c\u5c55\u793a", None))
        self.label_title.setText(QCoreApplication.translate("MainWindow", u"yolov5\u706b\u707e\u70df\u96fe\u8bc6\u522b\u8b66\u62a5\u7cfb\u7edf", None))
#if QT_CONFIG(tooltip)
        self.pushButton_logo.setToolTip(QCoreApplication.translate("MainWindow", u"\u8f6f\u4ef6\u4fe1\u606f", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_logo.setText("")
        self.label_is_save.setText(QCoreApplication.translate("MainWindow", u"\u662f\u5426\u4fdd\u5b58\u7ed3\u679c\uff1a", None))
        self.checkBox_is_save.setText("")
        self.checkBox_is_alarm.setText("")
    # retranslateUi

